name: ADMIN PROD CI&CD setup
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1
        with:
          node-version: '14.x'
      - name: Run build task
        run:  yarn build:prod
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync build s3://${{ secrets.S3_BUCKET_PROD }} --delete
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{
          secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} --paths "/*"```
